[package]
name = "day-3"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "part-1"
path = "src/bin/part_1.rs"

[[bin]]
name = "part-2"
path = "src/bin/part_2.rs"

[dependencies]
